spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: lb://EMPLOYEE
          predicates:
            - Path=/api/v1/employees/**
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://tracing:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
