logging:
  level:
    org.flywaydb: DEBUG
    sql: info
    org.springframework.cloud: DEBUG
spring:
  messages:
    encoding: UTF-8
    basename: messages
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - employee
    default-schema: employee
  jpa:
    show-sql: true
  boot:
    admin:
      client:
        enabled: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://tracing:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8082/realms/java-microservices
#            user-name-attribute: preferred_username
#        registration:
#          employee-app:
#            provider: keycloak
#            client-id: employee-app
#            client-secret: 0JnXSRZPopcPVO3RFCodLMGevrRdQAJw
#            scope:
#              - openid
#              - edit_client
#              - view_client
#              - microprofile-jwt
#            authorization-grant-type: authorization_code
